# Generated by Django 4.1.7 on 2023-03-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reporter",
            name="full_name",
            field=models.CharField(max_length=71),
        )
    ]
