# Generated by Django 4.1.7 on 2023-03-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("testapp", "0002_reporter_handle")]

    operations = [
        migrations.AddField(
            model_name="reporter", name="level", field=models.IntegerField(null=True)
        )
    ]
