name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {django: '==4.2.*', python: '3.11'}
          - {django: '==4.2.*', python: '3.10'}
          - {django: '==4.2.*', python: '3.9'}
          - {django: '==4.2.*', python: '3.8'}

          - {django: '~=4.1.3', python: '3.11'}
          - {django: '==4.1.*', python: '3.10'}
          - {django: '==4.1.*', python: '3.9'}
          - {django: '==4.1.*', python: '3.8'}

          - {django: '==4.0.*', python: '3.10'}
          - {django: '==4.0.*', python: '3.9'}
          - {django: '==4.0.*', python: '3.8'}

          - {django: '~=3.2.9', python: '3.10'}
          - {django: '==3.2.*', python: '3.9'}
          - {django: '==3.2.*', python: '3.8'}

          - {django: '~=3.1.3', python: '3.9'}
          - {django: '==3.1.*', python: '3.8'}

          - {django: '~=3.0.11', python: '3.9'}
          - {django: '==3.0.*', python: '3.8'}

          - {django: '~=2.2.17', python: '3.9'}
          - {django: '~=2.2.8', python: '3.8'}
    steps:
      - uses: actions/checkout@v3
      - name: Cache Poetry install
        uses: actions/cache@v3
        with:
          path: |
            /opt/pipx/venvs/poetry
            /opt/pipx_bin/poetry
          key: poetry-1.4.0-0
      - run: pipx install poetry==1.4.0
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: 'poetry'
      - run: poetry run pip install --pre 'django${{ matrix.django }}'
      - run: poetry install --no-interaction --with=dev
      - run: poetry run pytest -vv

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Poetry install
        uses: actions/cache@v3
        with:
          path: |
            /opt/pipx/venvs/poetry
            /opt/pipx_bin/poetry
          key: poetry-1.4.0-0
      - run: pipx install poetry==1.4.0
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: 'poetry'
      - run: poetry install --no-interaction --only=dev
      - name: Set PY
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
      - name: Cache pre-commit repos
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ env.PY }}-${{ hashFiles('.pre-commit-config.yaml') }}
      - run: poetry run pre-commit run --all-files

  typing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Poetry install
        uses: actions/cache@v3
        with:
          path: |
            /opt/pipx/venvs/poetry
            /opt/pipx_bin/poetry
          key: poetry-1.4.0-0
      - run: pipx install poetry==1.4.0
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: 'poetry'
      - name: Cache mypy
        uses: actions/cache@v3
        with:
          path: ./.mypy_cache
          key: mypy-3.8-${{ hashFiles('pyproject.toml') }}
      - run: poetry install --no-interaction --with=dev
      - run: poetry run mypy
